//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperacionesTopazWeb.wsUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnPerfil", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnPerfil : UtilitarioCrk.wsSeguridad.enBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Codigo_EquivalenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descripcion_EquivalenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMVLPerfilOpcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bEliminadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bPrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bProgramadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bRegistroBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bSinFechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dtFechaFinalAsignacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dtFechaInicioAsignacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCantidadCargosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCargoAsociadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCodigoEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCodigoNivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iContadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iFlagDMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdMVLPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdMvlOpcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdMvlOpcionPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCargoAsociadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sEquivalenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFechaAsociacionCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombrePerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sPerfilPrimarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int siEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short siMotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vFechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNombreObjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNombreOpcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo_Equivalencia {
            get {
                return this.Codigo_EquivalenciaField;
            }
            set {
                this.Codigo_EquivalenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion_Equivalencia {
            get {
                return this.Descripcion_EquivalenciaField;
            }
            set {
                this.Descripcion_EquivalenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMVLPerfilOpcion {
            get {
                return this.IdMVLPerfilOpcionField;
            }
            set {
                this.IdMVLPerfilOpcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bEliminado {
            get {
                return this.bEliminadoField;
            }
            set {
                this.bEliminadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bPrincipal {
            get {
                return this.bPrincipalField;
            }
            set {
                this.bPrincipalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bProgramado {
            get {
                return this.bProgramadoField;
            }
            set {
                this.bProgramadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bRegistroBD {
            get {
                return this.bRegistroBDField;
            }
            set {
                this.bRegistroBDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bSinFechaFin {
            get {
                return this.bSinFechaFinField;
            }
            set {
                this.bSinFechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dtFechaFinalAsignacion {
            get {
                return this.dtFechaFinalAsignacionField;
            }
            set {
                this.dtFechaFinalAsignacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dtFechaInicioAsignacion {
            get {
                return this.dtFechaInicioAsignacionField;
            }
            set {
                this.dtFechaInicioAsignacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCantidadCargos {
            get {
                return this.iCantidadCargosField;
            }
            set {
                this.iCantidadCargosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCargoAsociado {
            get {
                return this.iCargoAsociadoField;
            }
            set {
                this.iCargoAsociadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCodigoEstado {
            get {
                return this.iCodigoEstadoField;
            }
            set {
                this.iCodigoEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCodigoNivel {
            get {
                return this.iCodigoNivelField;
            }
            set {
                this.iCodigoNivelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iContador {
            get {
                return this.iContadorField;
            }
            set {
                this.iContadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iFlagDML {
            get {
                return this.iFlagDMLField;
            }
            set {
                this.iFlagDMLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdCargo {
            get {
                return this.iIdCargoField;
            }
            set {
                this.iIdCargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdMVLPerfil {
            get {
                return this.iIdMVLPerfilField;
            }
            set {
                this.iIdMVLPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdMvlOpcion {
            get {
                return this.iIdMvlOpcionField;
            }
            set {
                this.iIdMvlOpcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdMvlOpcionPadre {
            get {
                return this.iIdMvlOpcionPadreField;
            }
            set {
                this.iIdMvlOpcionPadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdPerfil {
            get {
                return this.iIdPerfilField;
            }
            set {
                this.iIdPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdUsuario {
            get {
                return this.iIdUsuarioField;
            }
            set {
                this.iIdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCargoAsociado {
            get {
                return this.sCargoAsociadoField;
            }
            set {
                this.sCargoAsociadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sEquivalencia {
            get {
                return this.sEquivalenciaField;
            }
            set {
                this.sEquivalenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFechaAsociacionCargo {
            get {
                return this.sFechaAsociacionCargoField;
            }
            set {
                this.sFechaAsociacionCargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMotivo {
            get {
                return this.sMotivoField;
            }
            set {
                this.sMotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombrePerfil {
            get {
                return this.sNombrePerfilField;
            }
            set {
                this.sNombrePerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sPerfilPrimario {
            get {
                return this.sPerfilPrimarioField;
            }
            set {
                this.sPerfilPrimarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int siEstado {
            get {
                return this.siEstadoField;
            }
            set {
                this.siEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short siMotivo {
            get {
                return this.siMotivoField;
            }
            set {
                this.siMotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vFechaRegistro {
            get {
                return this.vFechaRegistroField;
            }
            set {
                this.vFechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNombreObjeto {
            get {
                return this.vNombreObjetoField;
            }
            set {
                this.vNombreObjetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNombreOpcion {
            get {
                return this.vNombreOpcionField;
            }
            set {
                this.vNombreOpcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnOficina", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnOficina : UtilitarioCrk.wsSeguridad.enBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVtipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bEliminadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bPrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bRegistroBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dtFechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dtFechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iConsultasRepetidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iConsultasTotalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iConsultasUnicasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iFlagDMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdZonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iTipoOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCodigoAgenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCodigoSunatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCodigoUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sDescripcionUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFechaConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sIdOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombre_ZonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sOficinaPrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTipoOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTipoZonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int siEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vAnexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vEquivalenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vTelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVtipo {
            get {
                return this.IdVtipoField;
            }
            set {
                this.IdVtipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEstado {
            get {
                return this.NombreEstadoField;
            }
            set {
                this.NombreEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bEliminado {
            get {
                return this.bEliminadoField;
            }
            set {
                this.bEliminadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bPrincipal {
            get {
                return this.bPrincipalField;
            }
            set {
                this.bPrincipalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bRegistroBD {
            get {
                return this.bRegistroBDField;
            }
            set {
                this.bRegistroBDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dtFechaFin {
            get {
                return this.dtFechaFinField;
            }
            set {
                this.dtFechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dtFechaInicio {
            get {
                return this.dtFechaInicioField;
            }
            set {
                this.dtFechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iConsultasRepetidas {
            get {
                return this.iConsultasRepetidasField;
            }
            set {
                this.iConsultasRepetidasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iConsultasTotales {
            get {
                return this.iConsultasTotalesField;
            }
            set {
                this.iConsultasTotalesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iConsultasUnicas {
            get {
                return this.iConsultasUnicasField;
            }
            set {
                this.iConsultasUnicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iFlagDML {
            get {
                return this.iFlagDMLField;
            }
            set {
                this.iFlagDMLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdOficina {
            get {
                return this.iIdOficinaField;
            }
            set {
                this.iIdOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdRegion {
            get {
                return this.iIdRegionField;
            }
            set {
                this.iIdRegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdUsuario {
            get {
                return this.iIdUsuarioField;
            }
            set {
                this.iIdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdZona {
            get {
                return this.iIdZonaField;
            }
            set {
                this.iIdZonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iTipoOficina {
            get {
                return this.iTipoOficinaField;
            }
            set {
                this.iTipoOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCargo {
            get {
                return this.sCargoField;
            }
            set {
                this.sCargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCodigoAgencia {
            get {
                return this.sCodigoAgenciaField;
            }
            set {
                this.sCodigoAgenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCodigoSunat {
            get {
                return this.sCodigoSunatField;
            }
            set {
                this.sCodigoSunatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCodigoUbigeo {
            get {
                return this.sCodigoUbigeoField;
            }
            set {
                this.sCodigoUbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDescripcionUbigeo {
            get {
                return this.sDescripcionUbigeoField;
            }
            set {
                this.sDescripcionUbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFechaConsulta {
            get {
                return this.sFechaConsultaField;
            }
            set {
                this.sFechaConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sIdOficina {
            get {
                return this.sIdOficinaField;
            }
            set {
                this.sIdOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreOficina {
            get {
                return this.sNombreOficinaField;
            }
            set {
                this.sNombreOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreRegion {
            get {
                return this.sNombreRegionField;
            }
            set {
                this.sNombreRegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreUsuario {
            get {
                return this.sNombreUsuarioField;
            }
            set {
                this.sNombreUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombre_Zona {
            get {
                return this.sNombre_ZonaField;
            }
            set {
                this.sNombre_ZonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNumeroDocumento {
            get {
                return this.sNumeroDocumentoField;
            }
            set {
                this.sNumeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sOficinaPrincipal {
            get {
                return this.sOficinaPrincipalField;
            }
            set {
                this.sOficinaPrincipalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sTipoOficina {
            get {
                return this.sTipoOficinaField;
            }
            set {
                this.sTipoOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sTipoZona {
            get {
                return this.sTipoZonaField;
            }
            set {
                this.sTipoZonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int siEstado {
            get {
                return this.siEstadoField;
            }
            set {
                this.siEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vAnexo {
            get {
                return this.vAnexoField;
            }
            set {
                this.vAnexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vDireccion {
            get {
                return this.vDireccionField;
            }
            set {
                this.vDireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vEquivalencia {
            get {
                return this.vEquivalenciaField;
            }
            set {
                this.vEquivalenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vTelefono {
            get {
                return this.vTelefonoField;
            }
            set {
                this.vTelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnBloqueoUsuario", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnBloqueoUsuario : UtilitarioCrk.wsSeguridad.enBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bEliminadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bProgramadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdBloqueoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iSubTipoBloqueoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iTipoBloqueoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFechaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFechaInicioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bEliminado {
            get {
                return this.bEliminadoField;
            }
            set {
                this.bEliminadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bProgramado {
            get {
                return this.bProgramadoField;
            }
            set {
                this.bProgramadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iEstado {
            get {
                return this.iEstadoField;
            }
            set {
                this.iEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdBloqueoUsuario {
            get {
                return this.iIdBloqueoUsuarioField;
            }
            set {
                this.iIdBloqueoUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdUsuario {
            get {
                return this.iIdUsuarioField;
            }
            set {
                this.iIdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iSubTipoBloqueo {
            get {
                return this.iSubTipoBloqueoField;
            }
            set {
                this.iSubTipoBloqueoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iTipoBloqueo {
            get {
                return this.iTipoBloqueoField;
            }
            set {
                this.iTipoBloqueoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCodigoUsuario {
            get {
                return this.sCodigoUsuarioField;
            }
            set {
                this.sCodigoUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sComentario {
            get {
                return this.sComentarioField;
            }
            set {
                this.sComentarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFechaFinal {
            get {
                return this.sFechaFinalField;
            }
            set {
                this.sFechaFinalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFechaInicio {
            get {
                return this.sFechaInicioField;
            }
            set {
                this.sFechaInicioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsUsuario.IwsUsuario")]
    public interface IwsUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/ListarUsuario", ReplyAction="http://tempuri.org/IwsUsuario/ListarUsuarioResponse")]
        UtilitarioCrk.wsSeguridad.EnUsuario[] ListarUsuario(UtilitarioCrk.wsSeguridad.EnUsuario poenUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/ListarUsuario", ReplyAction="http://tempuri.org/IwsUsuario/ListarUsuarioResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario[]> ListarUsuarioAsync(UtilitarioCrk.wsSeguridad.EnUsuario poenUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSListarPerfil", ReplyAction="http://tempuri.org/IwsUsuario/WSListarPerfilResponse")]
        OperacionesTopazWeb.wsUsuario.EnPerfil[] WSListarPerfil(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSListarPerfil", ReplyAction="http://tempuri.org/IwsUsuario/WSListarPerfilResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsUsuario.EnPerfil[]> WSListarPerfilAsync(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSListarOficina", ReplyAction="http://tempuri.org/IwsUsuario/WSListarOficinaResponse")]
        OperacionesTopazWeb.wsUsuario.EnOficina[] WSListarOficina(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSListarOficina", ReplyAction="http://tempuri.org/IwsUsuario/WSListarOficinaResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsUsuario.EnOficina[]> WSListarOficinaAsync(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSBuscarUsuarioPorId", ReplyAction="http://tempuri.org/IwsUsuario/WSBuscarUsuarioPorIdResponse")]
        UtilitarioCrk.wsSeguridad.EnUsuario WSBuscarUsuarioPorId(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSBuscarUsuarioPorId", ReplyAction="http://tempuri.org/IwsUsuario/WSBuscarUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSBuscarUsuarioPorIdAsync(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSBuscarBloqueoUsuarioProgramado", ReplyAction="http://tempuri.org/IwsUsuario/WSBuscarBloqueoUsuarioProgramadoResponse")]
        OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario WSBuscarBloqueoUsuarioProgramado(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSBuscarBloqueoUsuarioProgramado", ReplyAction="http://tempuri.org/IwsUsuario/WSBuscarBloqueoUsuarioProgramadoResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario> WSBuscarBloqueoUsuarioProgramadoAsync(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSBuscarUsuarioPorNombre", ReplyAction="http://tempuri.org/IwsUsuario/WSBuscarUsuarioPorNombreResponse")]
        UtilitarioCrk.wsSeguridad.EnUsuario WSBuscarUsuarioPorNombre(string psCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSBuscarUsuarioPorNombre", ReplyAction="http://tempuri.org/IwsUsuario/WSBuscarUsuarioPorNombreResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSBuscarUsuarioPorNombreAsync(string psCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSObtenerRegistroBloqueoUsuarioInactivo", ReplyAction="http://tempuri.org/IwsUsuario/WSObtenerRegistroBloqueoUsuarioInactivoResponse")]
        OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario WSObtenerRegistroBloqueoUsuarioInactivo(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSObtenerRegistroBloqueoUsuarioInactivo", ReplyAction="http://tempuri.org/IwsUsuario/WSObtenerRegistroBloqueoUsuarioInactivoResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario> WSObtenerRegistroBloqueoUsuarioInactivoAsync(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSBuscarUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSBuscarUsuarioResponse")]
        bool WSBuscarUsuario(string psCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSBuscarUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSBuscarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> WSBuscarUsuarioAsync(string psCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSInhabilitarUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSInhabilitarUsuarioResponse")]
        int WSInhabilitarUsuario(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSInhabilitarUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSInhabilitarUsuarioResponse")]
        System.Threading.Tasks.Task<int> WSInhabilitarUsuarioAsync(int piCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSRegistrarUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSRegistrarUsuarioResponse")]
        int WSRegistrarUsuario(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario, OperacionesTopazWeb.wsUsuario.EnPerfil[] ploEnPerfil, OperacionesTopazWeb.wsUsuario.EnOficina[] ploEnOficina, string psNombres, string psApellidos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSRegistrarUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSRegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<int> WSRegistrarUsuarioAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario, OperacionesTopazWeb.wsUsuario.EnPerfil[] ploEnPerfil, OperacionesTopazWeb.wsUsuario.EnOficina[] ploEnOficina, string psNombres, string psApellidos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSEliminarBloqueoUsuarioProgramado", ReplyAction="http://tempuri.org/IwsUsuario/WSEliminarBloqueoUsuarioProgramadoResponse")]
        int WSEliminarBloqueoUsuarioProgramado(int piCodigoBloqueoUsuarioProgramado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSEliminarBloqueoUsuarioProgramado", ReplyAction="http://tempuri.org/IwsUsuario/WSEliminarBloqueoUsuarioProgramadoResponse")]
        System.Threading.Tasks.Task<int> WSEliminarBloqueoUsuarioProgramadoAsync(int piCodigoBloqueoUsuarioProgramado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSEditarUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSEditarUsuarioResponse")]
        int WSEditarUsuario(OperacionesTopazWeb.wsUsuario.EnPerfil[] ploEnPerfil, OperacionesTopazWeb.wsUsuario.EnOficina[] ploEnOficina, UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario, int pidPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSEditarUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSEditarUsuarioResponse")]
        System.Threading.Tasks.Task<int> WSEditarUsuarioAsync(OperacionesTopazWeb.wsUsuario.EnPerfil[] ploEnPerfil, OperacionesTopazWeb.wsUsuario.EnOficina[] ploEnOficina, UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario, int pidPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSRegistrarPersona", ReplyAction="http://tempuri.org/IwsUsuario/WSRegistrarPersonaResponse")]
        int WSRegistrarPersona(string psNombre, string psApellidos, UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSRegistrarPersona", ReplyAction="http://tempuri.org/IwsUsuario/WSRegistrarPersonaResponse")]
        System.Threading.Tasks.Task<int> WSRegistrarPersonaAsync(string psNombre, string psApellidos, UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSRegistrarBloqueoUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSRegistrarBloqueoUsuarioResponse")]
        int WSRegistrarBloqueoUsuario(OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario poEnBloqueoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSRegistrarBloqueoUsuario", ReplyAction="http://tempuri.org/IwsUsuario/WSRegistrarBloqueoUsuarioResponse")]
        System.Threading.Tasks.Task<int> WSRegistrarBloqueoUsuarioAsync(OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario poEnBloqueoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSEditarBloqueoUsuarioProgramado", ReplyAction="http://tempuri.org/IwsUsuario/WSEditarBloqueoUsuarioProgramadoResponse")]
        int WSEditarBloqueoUsuarioProgramado(OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario poEnBloqueoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsUsuario/WSEditarBloqueoUsuarioProgramado", ReplyAction="http://tempuri.org/IwsUsuario/WSEditarBloqueoUsuarioProgramadoResponse")]
        System.Threading.Tasks.Task<int> WSEditarBloqueoUsuarioProgramadoAsync(OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario poEnBloqueoUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsUsuarioChannel : OperacionesTopazWeb.wsUsuario.IwsUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsUsuarioClient : System.ServiceModel.ClientBase<OperacionesTopazWeb.wsUsuario.IwsUsuario>, OperacionesTopazWeb.wsUsuario.IwsUsuario {
        
        public IwsUsuarioClient() {
        }
        
        public IwsUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UtilitarioCrk.wsSeguridad.EnUsuario[] ListarUsuario(UtilitarioCrk.wsSeguridad.EnUsuario poenUsuario) {
            return base.Channel.ListarUsuario(poenUsuario);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario[]> ListarUsuarioAsync(UtilitarioCrk.wsSeguridad.EnUsuario poenUsuario) {
            return base.Channel.ListarUsuarioAsync(poenUsuario);
        }
        
        public OperacionesTopazWeb.wsUsuario.EnPerfil[] WSListarPerfil(int piCodigoUsuario) {
            return base.Channel.WSListarPerfil(piCodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsUsuario.EnPerfil[]> WSListarPerfilAsync(int piCodigoUsuario) {
            return base.Channel.WSListarPerfilAsync(piCodigoUsuario);
        }
        
        public OperacionesTopazWeb.wsUsuario.EnOficina[] WSListarOficina(int piCodigoUsuario) {
            return base.Channel.WSListarOficina(piCodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsUsuario.EnOficina[]> WSListarOficinaAsync(int piCodigoUsuario) {
            return base.Channel.WSListarOficinaAsync(piCodigoUsuario);
        }
        
        public UtilitarioCrk.wsSeguridad.EnUsuario WSBuscarUsuarioPorId(int piCodigoUsuario) {
            return base.Channel.WSBuscarUsuarioPorId(piCodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSBuscarUsuarioPorIdAsync(int piCodigoUsuario) {
            return base.Channel.WSBuscarUsuarioPorIdAsync(piCodigoUsuario);
        }
        
        public OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario WSBuscarBloqueoUsuarioProgramado(int piCodigoUsuario) {
            return base.Channel.WSBuscarBloqueoUsuarioProgramado(piCodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario> WSBuscarBloqueoUsuarioProgramadoAsync(int piCodigoUsuario) {
            return base.Channel.WSBuscarBloqueoUsuarioProgramadoAsync(piCodigoUsuario);
        }
        
        public UtilitarioCrk.wsSeguridad.EnUsuario WSBuscarUsuarioPorNombre(string psCodigoUsuario) {
            return base.Channel.WSBuscarUsuarioPorNombre(psCodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSBuscarUsuarioPorNombreAsync(string psCodigoUsuario) {
            return base.Channel.WSBuscarUsuarioPorNombreAsync(psCodigoUsuario);
        }
        
        public OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario WSObtenerRegistroBloqueoUsuarioInactivo(int piCodigoUsuario) {
            return base.Channel.WSObtenerRegistroBloqueoUsuarioInactivo(piCodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario> WSObtenerRegistroBloqueoUsuarioInactivoAsync(int piCodigoUsuario) {
            return base.Channel.WSObtenerRegistroBloqueoUsuarioInactivoAsync(piCodigoUsuario);
        }
        
        public bool WSBuscarUsuario(string psCodigoUsuario) {
            return base.Channel.WSBuscarUsuario(psCodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> WSBuscarUsuarioAsync(string psCodigoUsuario) {
            return base.Channel.WSBuscarUsuarioAsync(psCodigoUsuario);
        }
        
        public int WSInhabilitarUsuario(int piCodigoUsuario) {
            return base.Channel.WSInhabilitarUsuario(piCodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<int> WSInhabilitarUsuarioAsync(int piCodigoUsuario) {
            return base.Channel.WSInhabilitarUsuarioAsync(piCodigoUsuario);
        }
        
        public int WSRegistrarUsuario(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario, OperacionesTopazWeb.wsUsuario.EnPerfil[] ploEnPerfil, OperacionesTopazWeb.wsUsuario.EnOficina[] ploEnOficina, string psNombres, string psApellidos) {
            return base.Channel.WSRegistrarUsuario(poEnUsuario, ploEnPerfil, ploEnOficina, psNombres, psApellidos);
        }
        
        public System.Threading.Tasks.Task<int> WSRegistrarUsuarioAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario, OperacionesTopazWeb.wsUsuario.EnPerfil[] ploEnPerfil, OperacionesTopazWeb.wsUsuario.EnOficina[] ploEnOficina, string psNombres, string psApellidos) {
            return base.Channel.WSRegistrarUsuarioAsync(poEnUsuario, ploEnPerfil, ploEnOficina, psNombres, psApellidos);
        }
        
        public int WSEliminarBloqueoUsuarioProgramado(int piCodigoBloqueoUsuarioProgramado) {
            return base.Channel.WSEliminarBloqueoUsuarioProgramado(piCodigoBloqueoUsuarioProgramado);
        }
        
        public System.Threading.Tasks.Task<int> WSEliminarBloqueoUsuarioProgramadoAsync(int piCodigoBloqueoUsuarioProgramado) {
            return base.Channel.WSEliminarBloqueoUsuarioProgramadoAsync(piCodigoBloqueoUsuarioProgramado);
        }
        
        public int WSEditarUsuario(OperacionesTopazWeb.wsUsuario.EnPerfil[] ploEnPerfil, OperacionesTopazWeb.wsUsuario.EnOficina[] ploEnOficina, UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario, int pidPersona) {
            return base.Channel.WSEditarUsuario(ploEnPerfil, ploEnOficina, poEnUsuario, pidPersona);
        }
        
        public System.Threading.Tasks.Task<int> WSEditarUsuarioAsync(OperacionesTopazWeb.wsUsuario.EnPerfil[] ploEnPerfil, OperacionesTopazWeb.wsUsuario.EnOficina[] ploEnOficina, UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario, int pidPersona) {
            return base.Channel.WSEditarUsuarioAsync(ploEnPerfil, ploEnOficina, poEnUsuario, pidPersona);
        }
        
        public int WSRegistrarPersona(string psNombre, string psApellidos, UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSRegistrarPersona(psNombre, psApellidos, poEnUsuario);
        }
        
        public System.Threading.Tasks.Task<int> WSRegistrarPersonaAsync(string psNombre, string psApellidos, UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSRegistrarPersonaAsync(psNombre, psApellidos, poEnUsuario);
        }
        
        public int WSRegistrarBloqueoUsuario(OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario poEnBloqueoUsuario) {
            return base.Channel.WSRegistrarBloqueoUsuario(poEnBloqueoUsuario);
        }
        
        public System.Threading.Tasks.Task<int> WSRegistrarBloqueoUsuarioAsync(OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario poEnBloqueoUsuario) {
            return base.Channel.WSRegistrarBloqueoUsuarioAsync(poEnBloqueoUsuario);
        }
        
        public int WSEditarBloqueoUsuarioProgramado(OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario poEnBloqueoUsuario) {
            return base.Channel.WSEditarBloqueoUsuarioProgramado(poEnBloqueoUsuario);
        }
        
        public System.Threading.Tasks.Task<int> WSEditarBloqueoUsuarioProgramadoAsync(OperacionesTopazWeb.wsUsuario.EnBloqueoUsuario poEnBloqueoUsuario) {
            return base.Channel.WSEditarBloqueoUsuarioProgramadoAsync(poEnBloqueoUsuario);
        }
    }
}
