//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperacionesTopazWeb.wsSeguridad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnUsuarioLoginWAPI", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnUsuarioLoginWAPI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bValidarSesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iEntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCodigoMACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNumeroTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSesionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short siOrigenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bToken {
            get {
                return this.bTokenField;
            }
            set {
                if ((this.bTokenField.Equals(value) != true)) {
                    this.bTokenField = value;
                    this.RaisePropertyChanged("bToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bValidarSesion {
            get {
                return this.bValidarSesionField;
            }
            set {
                if ((this.bValidarSesionField.Equals(value) != true)) {
                    this.bValidarSesionField = value;
                    this.RaisePropertyChanged("bValidarSesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iEntidad {
            get {
                return this.iEntidadField;
            }
            set {
                if ((this.iEntidadField.Equals(value) != true)) {
                    this.iEntidadField = value;
                    this.RaisePropertyChanged("iEntidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCodigoMAC {
            get {
                return this.sCodigoMACField;
            }
            set {
                if ((object.ReferenceEquals(this.sCodigoMACField, value) != true)) {
                    this.sCodigoMACField = value;
                    this.RaisePropertyChanged("sCodigoMAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNumeroTelefono {
            get {
                return this.sNumeroTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.sNumeroTelefonoField, value) != true)) {
                    this.sNumeroTelefonoField = value;
                    this.RaisePropertyChanged("sNumeroTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sPassword {
            get {
                return this.sPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.sPasswordField, value) != true)) {
                    this.sPasswordField = value;
                    this.RaisePropertyChanged("sPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSesionId {
            get {
                return this.sSesionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.sSesionIdField, value) != true)) {
                    this.sSesionIdField = value;
                    this.RaisePropertyChanged("sSesionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sUsuario {
            get {
                return this.sUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.sUsuarioField, value) != true)) {
                    this.sUsuarioField = value;
                    this.RaisePropertyChanged("sUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short siOrigen {
            get {
                return this.siOrigenField;
            }
            set {
                if ((this.siOrigenField.Equals(value) != true)) {
                    this.siOrigenField = value;
                    this.RaisePropertyChanged("siOrigen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnUsuarioWAPI", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnUsuarioWAPI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OperacionesTopazWeb.wsSeguridad.EnMenuWAPI[] loMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreOficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombrePerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sRefreshTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSesionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short siEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short siOrigenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bAcceso {
            get {
                return this.bAccesoField;
            }
            set {
                if ((this.bAccesoField.Equals(value) != true)) {
                    this.bAccesoField = value;
                    this.RaisePropertyChanged("bAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdCargo {
            get {
                return this.iIdCargoField;
            }
            set {
                if ((this.iIdCargoField.Equals(value) != true)) {
                    this.iIdCargoField = value;
                    this.RaisePropertyChanged("iIdCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdOficina {
            get {
                return this.iIdOficinaField;
            }
            set {
                if ((this.iIdOficinaField.Equals(value) != true)) {
                    this.iIdOficinaField = value;
                    this.RaisePropertyChanged("iIdOficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdPerfil {
            get {
                return this.iIdPerfilField;
            }
            set {
                if ((this.iIdPerfilField.Equals(value) != true)) {
                    this.iIdPerfilField = value;
                    this.RaisePropertyChanged("iIdPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdUsuario {
            get {
                return this.iIdUsuarioField;
            }
            set {
                if ((this.iIdUsuarioField.Equals(value) != true)) {
                    this.iIdUsuarioField = value;
                    this.RaisePropertyChanged("iIdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iRespuesta {
            get {
                return this.iRespuestaField;
            }
            set {
                if ((this.iRespuestaField.Equals(value) != true)) {
                    this.iRespuestaField = value;
                    this.RaisePropertyChanged("iRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iTipoDocumento {
            get {
                return this.iTipoDocumentoField;
            }
            set {
                if ((this.iTipoDocumentoField.Equals(value) != true)) {
                    this.iTipoDocumentoField = value;
                    this.RaisePropertyChanged("iTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OperacionesTopazWeb.wsSeguridad.EnMenuWAPI[] loMenu {
            get {
                return this.loMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.loMenuField, value) != true)) {
                    this.loMenuField = value;
                    this.RaisePropertyChanged("loMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sApellidos {
            get {
                return this.sApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.sApellidosField, value) != true)) {
                    this.sApellidosField = value;
                    this.RaisePropertyChanged("sApellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCodigoUsuario {
            get {
                return this.sCodigoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.sCodigoUsuarioField, value) != true)) {
                    this.sCodigoUsuarioField = value;
                    this.RaisePropertyChanged("sCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCorreo {
            get {
                return this.sCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.sCorreoField, value) != true)) {
                    this.sCorreoField = value;
                    this.RaisePropertyChanged("sCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreCargo {
            get {
                return this.sNombreCargoField;
            }
            set {
                if ((object.ReferenceEquals(this.sNombreCargoField, value) != true)) {
                    this.sNombreCargoField = value;
                    this.RaisePropertyChanged("sNombreCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreCompleto {
            get {
                return this.sNombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.sNombreCompletoField, value) != true)) {
                    this.sNombreCompletoField = value;
                    this.RaisePropertyChanged("sNombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreEstado {
            get {
                return this.sNombreEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.sNombreEstadoField, value) != true)) {
                    this.sNombreEstadoField = value;
                    this.RaisePropertyChanged("sNombreEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreOficina {
            get {
                return this.sNombreOficinaField;
            }
            set {
                if ((object.ReferenceEquals(this.sNombreOficinaField, value) != true)) {
                    this.sNombreOficinaField = value;
                    this.RaisePropertyChanged("sNombreOficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombrePerfil {
            get {
                return this.sNombrePerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.sNombrePerfilField, value) != true)) {
                    this.sNombrePerfilField = value;
                    this.RaisePropertyChanged("sNombrePerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombres {
            get {
                return this.sNombresField;
            }
            set {
                if ((object.ReferenceEquals(this.sNombresField, value) != true)) {
                    this.sNombresField = value;
                    this.RaisePropertyChanged("sNombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNumeroDocumento {
            get {
                return this.sNumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.sNumeroDocumentoField, value) != true)) {
                    this.sNumeroDocumentoField = value;
                    this.RaisePropertyChanged("sNumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sRefreshToken {
            get {
                return this.sRefreshTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.sRefreshTokenField, value) != true)) {
                    this.sRefreshTokenField = value;
                    this.RaisePropertyChanged("sRefreshToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSesionId {
            get {
                return this.sSesionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.sSesionIdField, value) != true)) {
                    this.sSesionIdField = value;
                    this.RaisePropertyChanged("sSesionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sToken {
            get {
                return this.sTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.sTokenField, value) != true)) {
                    this.sTokenField = value;
                    this.RaisePropertyChanged("sToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short siEstado {
            get {
                return this.siEstadoField;
            }
            set {
                if ((this.siEstadoField.Equals(value) != true)) {
                    this.siEstadoField = value;
                    this.RaisePropertyChanged("siEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short siOrigen {
            get {
                return this.siOrigenField;
            }
            set {
                if ((this.siOrigenField.Equals(value) != true)) {
                    this.siOrigenField = value;
                    this.RaisePropertyChanged("siOrigen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnMenuWAPI", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnMenuWAPI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdHijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdSubModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sModuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSubModuloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdHijo {
            get {
                return this.iIdHijoField;
            }
            set {
                if ((this.iIdHijoField.Equals(value) != true)) {
                    this.iIdHijoField = value;
                    this.RaisePropertyChanged("iIdHijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdMenu {
            get {
                return this.iIdMenuField;
            }
            set {
                if ((this.iIdMenuField.Equals(value) != true)) {
                    this.iIdMenuField = value;
                    this.RaisePropertyChanged("iIdMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdModulo {
            get {
                return this.iIdModuloField;
            }
            set {
                if ((this.iIdModuloField.Equals(value) != true)) {
                    this.iIdModuloField = value;
                    this.RaisePropertyChanged("iIdModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdPadre {
            get {
                return this.iIdPadreField;
            }
            set {
                if ((this.iIdPadreField.Equals(value) != true)) {
                    this.iIdPadreField = value;
                    this.RaisePropertyChanged("iIdPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdSubModulo {
            get {
                return this.iIdSubModuloField;
            }
            set {
                if ((this.iIdSubModuloField.Equals(value) != true)) {
                    this.iIdSubModuloField = value;
                    this.RaisePropertyChanged("iIdSubModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFormulario {
            get {
                return this.sFormularioField;
            }
            set {
                if ((object.ReferenceEquals(this.sFormularioField, value) != true)) {
                    this.sFormularioField = value;
                    this.RaisePropertyChanged("sFormulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMenu {
            get {
                return this.sMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.sMenuField, value) != true)) {
                    this.sMenuField = value;
                    this.RaisePropertyChanged("sMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sModulo {
            get {
                return this.sModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.sModuloField, value) != true)) {
                    this.sModuloField = value;
                    this.RaisePropertyChanged("sModulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSubModulo {
            get {
                return this.sSubModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.sSubModuloField, value) != true)) {
                    this.sSubModuloField = value;
                    this.RaisePropertyChanged("sSubModulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnBloqueoUsuarioWAPI", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnBloqueoUsuarioWAPI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bRequiereTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNroDNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short siResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bRequiereToken {
            get {
                return this.bRequiereTokenField;
            }
            set {
                if ((this.bRequiereTokenField.Equals(value) != true)) {
                    this.bRequiereTokenField = value;
                    this.RaisePropertyChanged("bRequiereToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensaje {
            get {
                return this.sMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeField, value) != true)) {
                    this.sMensajeField = value;
                    this.RaisePropertyChanged("sMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNroDNI {
            get {
                return this.sNroDNIField;
            }
            set {
                if ((object.ReferenceEquals(this.sNroDNIField, value) != true)) {
                    this.sNroDNIField = value;
                    this.RaisePropertyChanged("sNroDNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sToken {
            get {
                return this.sTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.sTokenField, value) != true)) {
                    this.sTokenField = value;
                    this.RaisePropertyChanged("sToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sUsuario {
            get {
                return this.sUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.sUsuarioField, value) != true)) {
                    this.sUsuarioField = value;
                    this.RaisePropertyChanged("sUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short siResultado {
            get {
                return this.siResultadoField;
            }
            set {
                if ((this.siResultadoField.Equals(value) != true)) {
                    this.siResultadoField = value;
                    this.RaisePropertyChanged("siResultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSeguridad.IwsSEA")]
    public interface IwsSEA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarUsuario", ReplyAction="http://tempuri.org/IwsSEA/WSValidarUsuarioResponse")]
        UtilitarioCrk.wsSeguridad.EnUsuario WSValidarUsuario(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarUsuario", ReplyAction="http://tempuri.org/IwsSEA/WSValidarUsuarioResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSValidarUsuarioAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarUsuarioMovil", ReplyAction="http://tempuri.org/IwsSEA/WSValidarUsuarioMovilResponse")]
        UtilitarioCrk.wsSeguridad.EnUsuario WSValidarUsuarioMovil(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarUsuarioMovil", ReplyAction="http://tempuri.org/IwsSEA/WSValidarUsuarioMovilResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSValidarUsuarioMovilAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSObtenerModuloUsuario", ReplyAction="http://tempuri.org/IwsSEA/WSObtenerModuloUsuarioResponse")]
        UtilitarioCrk.wsSeguridad.EnModulo[] WSObtenerModuloUsuario(string pvalor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSObtenerModuloUsuario", ReplyAction="http://tempuri.org/IwsSEA/WSObtenerModuloUsuarioResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnModulo[]> WSObtenerModuloUsuarioAsync(string pvalor1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSObtenerMenuModuloUsuario", ReplyAction="http://tempuri.org/IwsSEA/WSObtenerMenuModuloUsuarioResponse")]
        UtilitarioCrk.wsSeguridad.EnMenu[] WSObtenerMenuModuloUsuario(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSObtenerMenuModuloUsuario", ReplyAction="http://tempuri.org/IwsSEA/WSObtenerMenuModuloUsuarioResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnMenu[]> WSObtenerMenuModuloUsuarioAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarUsuarioMovilAyni", ReplyAction="http://tempuri.org/IwsSEA/WSValidarUsuarioMovilAyniResponse")]
        UtilitarioCrk.wsSeguridad.EnUsuario WSValidarUsuarioMovilAyni(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarUsuarioMovilAyni", ReplyAction="http://tempuri.org/IwsSEA/WSValidarUsuarioMovilAyniResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSValidarUsuarioMovilAyniAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarAD_CarteraDigital", ReplyAction="http://tempuri.org/IwsSEA/WSValidarAD_CarteraDigitalResponse")]
        UtilitarioCrk.wsSeguridad.EnUsuario WSValidarAD_CarteraDigital(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarAD_CarteraDigital", ReplyAction="http://tempuri.org/IwsSEA/WSValidarAD_CarteraDigitalResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSValidarAD_CarteraDigitalAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSAutenticacionAD", ReplyAction="http://tempuri.org/IwsSEA/WSAutenticacionADResponse")]
        UtilitarioCrk.wsSeguridad.EnUsuario WSAutenticacionAD(UtilitarioCrk.wsSeguridad.EnUsuario poUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSAutenticacionAD", ReplyAction="http://tempuri.org/IwsSEA/WSAutenticacionADResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSAutenticacionADAsync(UtilitarioCrk.wsSeguridad.EnUsuario poUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidacionAD", ReplyAction="http://tempuri.org/IwsSEA/WSValidacionADResponse")]
        UtilitarioCrk.wsSeguridad.EnUsuario WSValidacionAD(string psNombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidacionAD", ReplyAction="http://tempuri.org/IwsSEA/WSValidacionADResponse")]
        System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSValidacionADAsync(string psNombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSAutenticacionWAPI", ReplyAction="http://tempuri.org/IwsSEA/WSAutenticacionWAPIResponse")]
        OperacionesTopazWeb.wsSeguridad.EnUsuarioWAPI WSAutenticacionWAPI(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSAutenticacionWAPI", ReplyAction="http://tempuri.org/IwsSEA/WSAutenticacionWAPIResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsSeguridad.EnUsuarioWAPI> WSAutenticacionWAPIAsync(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSObtenerUsuarioWAPI", ReplyAction="http://tempuri.org/IwsSEA/WSObtenerUsuarioWAPIResponse")]
        OperacionesTopazWeb.wsSeguridad.EnUsuarioWAPI WSObtenerUsuarioWAPI(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSObtenerUsuarioWAPI", ReplyAction="http://tempuri.org/IwsSEA/WSObtenerUsuarioWAPIResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsSeguridad.EnUsuarioWAPI> WSObtenerUsuarioWAPIAsync(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSCerrarSesionWAPI", ReplyAction="http://tempuri.org/IwsSEA/WSCerrarSesionWAPIResponse")]
        bool WSCerrarSesionWAPI(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSCerrarSesionWAPI", ReplyAction="http://tempuri.org/IwsSEA/WSCerrarSesionWAPIResponse")]
        System.Threading.Tasks.Task<bool> WSCerrarSesionWAPIAsync(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarAccesoMenuId", ReplyAction="http://tempuri.org/IwsSEA/WSValidarAccesoMenuIdResponse")]
        bool WSValidarAccesoMenuId(int piIdUsuario, int piIdMenu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarAccesoMenuId", ReplyAction="http://tempuri.org/IwsSEA/WSValidarAccesoMenuIdResponse")]
        System.Threading.Tasks.Task<bool> WSValidarAccesoMenuIdAsync(int piIdUsuario, int piIdMenu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarAccesoMenu", ReplyAction="http://tempuri.org/IwsSEA/WSValidarAccesoMenuResponse")]
        bool WSValidarAccesoMenu(int piIdUsuario, string psMenu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarAccesoMenu", ReplyAction="http://tempuri.org/IwsSEA/WSValidarAccesoMenuResponse")]
        System.Threading.Tasks.Task<bool> WSValidarAccesoMenuAsync(int piIdUsuario, string psMenu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarSesionWAPI", ReplyAction="http://tempuri.org/IwsSEA/WSValidarSesionWAPIResponse")]
        bool WSValidarSesionWAPI(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSValidarSesionWAPI", ReplyAction="http://tempuri.org/IwsSEA/WSValidarSesionWAPIResponse")]
        System.Threading.Tasks.Task<bool> WSValidarSesionWAPIAsync(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSDesbloquearUsuarioIntentoFallido", ReplyAction="http://tempuri.org/IwsSEA/WSDesbloquearUsuarioIntentoFallidoResponse")]
        OperacionesTopazWeb.wsSeguridad.EnBloqueoUsuarioWAPI WSDesbloquearUsuarioIntentoFallido(OperacionesTopazWeb.wsSeguridad.EnBloqueoUsuarioWAPI poBloqueoUsuarioWAPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSEA/WSDesbloquearUsuarioIntentoFallido", ReplyAction="http://tempuri.org/IwsSEA/WSDesbloquearUsuarioIntentoFallidoResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsSeguridad.EnBloqueoUsuarioWAPI> WSDesbloquearUsuarioIntentoFallidoAsync(OperacionesTopazWeb.wsSeguridad.EnBloqueoUsuarioWAPI poBloqueoUsuarioWAPI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsSEAChannel : OperacionesTopazWeb.wsSeguridad.IwsSEA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsSEAClient : System.ServiceModel.ClientBase<OperacionesTopazWeb.wsSeguridad.IwsSEA>, OperacionesTopazWeb.wsSeguridad.IwsSEA {
        
        public IwsSEAClient() {
        }
        
        public IwsSEAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsSEAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsSEAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsSEAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UtilitarioCrk.wsSeguridad.EnUsuario WSValidarUsuario(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSValidarUsuario(poEnUsuario);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSValidarUsuarioAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSValidarUsuarioAsync(poEnUsuario);
        }
        
        public UtilitarioCrk.wsSeguridad.EnUsuario WSValidarUsuarioMovil(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSValidarUsuarioMovil(poEnUsuario);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSValidarUsuarioMovilAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSValidarUsuarioMovilAsync(poEnUsuario);
        }
        
        public UtilitarioCrk.wsSeguridad.EnModulo[] WSObtenerModuloUsuario(string pvalor1) {
            return base.Channel.WSObtenerModuloUsuario(pvalor1);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnModulo[]> WSObtenerModuloUsuarioAsync(string pvalor1) {
            return base.Channel.WSObtenerModuloUsuarioAsync(pvalor1);
        }
        
        public UtilitarioCrk.wsSeguridad.EnMenu[] WSObtenerMenuModuloUsuario(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSObtenerMenuModuloUsuario(poEnUsuario);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnMenu[]> WSObtenerMenuModuloUsuarioAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSObtenerMenuModuloUsuarioAsync(poEnUsuario);
        }
        
        public UtilitarioCrk.wsSeguridad.EnUsuario WSValidarUsuarioMovilAyni(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSValidarUsuarioMovilAyni(poEnUsuario);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSValidarUsuarioMovilAyniAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSValidarUsuarioMovilAyniAsync(poEnUsuario);
        }
        
        public UtilitarioCrk.wsSeguridad.EnUsuario WSValidarAD_CarteraDigital(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSValidarAD_CarteraDigital(poEnUsuario);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSValidarAD_CarteraDigitalAsync(UtilitarioCrk.wsSeguridad.EnUsuario poEnUsuario) {
            return base.Channel.WSValidarAD_CarteraDigitalAsync(poEnUsuario);
        }
        
        public UtilitarioCrk.wsSeguridad.EnUsuario WSAutenticacionAD(UtilitarioCrk.wsSeguridad.EnUsuario poUsuario) {
            return base.Channel.WSAutenticacionAD(poUsuario);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSAutenticacionADAsync(UtilitarioCrk.wsSeguridad.EnUsuario poUsuario) {
            return base.Channel.WSAutenticacionADAsync(poUsuario);
        }
        
        public UtilitarioCrk.wsSeguridad.EnUsuario WSValidacionAD(string psNombreUsuario) {
            return base.Channel.WSValidacionAD(psNombreUsuario);
        }
        
        public System.Threading.Tasks.Task<UtilitarioCrk.wsSeguridad.EnUsuario> WSValidacionADAsync(string psNombreUsuario) {
            return base.Channel.WSValidacionADAsync(psNombreUsuario);
        }
        
        public OperacionesTopazWeb.wsSeguridad.EnUsuarioWAPI WSAutenticacionWAPI(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI) {
            return base.Channel.WSAutenticacionWAPI(poUsuarioLoginWAPI);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsSeguridad.EnUsuarioWAPI> WSAutenticacionWAPIAsync(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI) {
            return base.Channel.WSAutenticacionWAPIAsync(poUsuarioLoginWAPI);
        }
        
        public OperacionesTopazWeb.wsSeguridad.EnUsuarioWAPI WSObtenerUsuarioWAPI(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI) {
            return base.Channel.WSObtenerUsuarioWAPI(poUsuarioLoginWAPI);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsSeguridad.EnUsuarioWAPI> WSObtenerUsuarioWAPIAsync(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI) {
            return base.Channel.WSObtenerUsuarioWAPIAsync(poUsuarioLoginWAPI);
        }
        
        public bool WSCerrarSesionWAPI(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI) {
            return base.Channel.WSCerrarSesionWAPI(poUsuarioLoginWAPI);
        }
        
        public System.Threading.Tasks.Task<bool> WSCerrarSesionWAPIAsync(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI) {
            return base.Channel.WSCerrarSesionWAPIAsync(poUsuarioLoginWAPI);
        }
        
        public bool WSValidarAccesoMenuId(int piIdUsuario, int piIdMenu) {
            return base.Channel.WSValidarAccesoMenuId(piIdUsuario, piIdMenu);
        }
        
        public System.Threading.Tasks.Task<bool> WSValidarAccesoMenuIdAsync(int piIdUsuario, int piIdMenu) {
            return base.Channel.WSValidarAccesoMenuIdAsync(piIdUsuario, piIdMenu);
        }
        
        public bool WSValidarAccesoMenu(int piIdUsuario, string psMenu) {
            return base.Channel.WSValidarAccesoMenu(piIdUsuario, psMenu);
        }
        
        public System.Threading.Tasks.Task<bool> WSValidarAccesoMenuAsync(int piIdUsuario, string psMenu) {
            return base.Channel.WSValidarAccesoMenuAsync(piIdUsuario, psMenu);
        }
        
        public bool WSValidarSesionWAPI(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI) {
            return base.Channel.WSValidarSesionWAPI(poUsuarioLoginWAPI);
        }
        
        public System.Threading.Tasks.Task<bool> WSValidarSesionWAPIAsync(OperacionesTopazWeb.wsSeguridad.EnUsuarioLoginWAPI poUsuarioLoginWAPI) {
            return base.Channel.WSValidarSesionWAPIAsync(poUsuarioLoginWAPI);
        }
        
        public OperacionesTopazWeb.wsSeguridad.EnBloqueoUsuarioWAPI WSDesbloquearUsuarioIntentoFallido(OperacionesTopazWeb.wsSeguridad.EnBloqueoUsuarioWAPI poBloqueoUsuarioWAPI) {
            return base.Channel.WSDesbloquearUsuarioIntentoFallido(poBloqueoUsuarioWAPI);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsSeguridad.EnBloqueoUsuarioWAPI> WSDesbloquearUsuarioIntentoFallidoAsync(OperacionesTopazWeb.wsSeguridad.EnBloqueoUsuarioWAPI poBloqueoUsuarioWAPI) {
            return base.Channel.WSDesbloquearUsuarioIntentoFallidoAsync(poBloqueoUsuarioWAPI);
        }
    }
}
