//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperacionesTopazWeb.wsGestion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnCorresponsaliaParametros", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnCorresponsaliaParametros : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCodigoOficinaUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAudIPCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAudMACCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sAudNombreUsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sDescripcionAccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCodigoOficinaUsuario {
            get {
                return this.iCodigoOficinaUsuarioField;
            }
            set {
                if ((this.iCodigoOficinaUsuarioField.Equals(value) != true)) {
                    this.iCodigoOficinaUsuarioField = value;
                    this.RaisePropertyChanged("iCodigoOficinaUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIAccion {
            get {
                return this.iIAccionField;
            }
            set {
                if ((this.iIAccionField.Equals(value) != true)) {
                    this.iIAccionField = value;
                    this.RaisePropertyChanged("iIAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIdUsuario {
            get {
                return this.iIdUsuarioField;
            }
            set {
                if ((this.iIdUsuarioField.Equals(value) != true)) {
                    this.iIdUsuarioField = value;
                    this.RaisePropertyChanged("iIdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAudIPCreacion {
            get {
                return this.sAudIPCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.sAudIPCreacionField, value) != true)) {
                    this.sAudIPCreacionField = value;
                    this.RaisePropertyChanged("sAudIPCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAudMACCreacion {
            get {
                return this.sAudMACCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.sAudMACCreacionField, value) != true)) {
                    this.sAudMACCreacionField = value;
                    this.RaisePropertyChanged("sAudMACCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sAudNombreUsuarioCreacion {
            get {
                return this.sAudNombreUsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.sAudNombreUsuarioCreacionField, value) != true)) {
                    this.sAudNombreUsuarioCreacionField = value;
                    this.RaisePropertyChanged("sAudNombreUsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDescripcionAccion {
            get {
                return this.sDescripcionAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.sDescripcionAccionField, value) != true)) {
                    this.sDescripcionAccionField = value;
                    this.RaisePropertyChanged("sDescripcionAccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnCorresponsalia", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnCorresponsalia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCantidadRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iIndicadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sDescripcionAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFechaProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombresCompletoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iAccion {
            get {
                return this.iAccionField;
            }
            set {
                if ((this.iAccionField.Equals(value) != true)) {
                    this.iAccionField = value;
                    this.RaisePropertyChanged("iAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCantidadRegistros {
            get {
                return this.iCantidadRegistrosField;
            }
            set {
                if ((this.iCantidadRegistrosField.Equals(value) != true)) {
                    this.iCantidadRegistrosField = value;
                    this.RaisePropertyChanged("iCantidadRegistros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iError {
            get {
                return this.iErrorField;
            }
            set {
                if ((this.iErrorField.Equals(value) != true)) {
                    this.iErrorField = value;
                    this.RaisePropertyChanged("iError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iIndicador {
            get {
                return this.iIndicadorField;
            }
            set {
                if ((this.iIndicadorField.Equals(value) != true)) {
                    this.iIndicadorField = value;
                    this.RaisePropertyChanged("iIndicador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDescripcionAccion {
            get {
                return this.sDescripcionAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.sDescripcionAccionField, value) != true)) {
                    this.sDescripcionAccionField = value;
                    this.RaisePropertyChanged("sDescripcionAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFechaProceso {
            get {
                return this.sFechaProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.sFechaProcesoField, value) != true)) {
                    this.sFechaProcesoField = value;
                    this.RaisePropertyChanged("sFechaProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensaje {
            get {
                return this.sMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeField, value) != true)) {
                    this.sMensajeField = value;
                    this.RaisePropertyChanged("sMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombresCompleto {
            get {
                return this.sNombresCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.sNombresCompletoField, value) != true)) {
                    this.sNombresCompletoField = value;
                    this.RaisePropertyChanged("sNombresCompleto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnCorresponsaliaDescargarPagos", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnCorresponsaliaDescargarPagos : UtilitarioCrk.wsSeguridad.enBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NRO_LINEAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dFechaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dFechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dFecha_IngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal dMonto_AplicarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal iImp_MoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal iInt_MoratorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iOficina_PagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nImpDepositadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nImp_OrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nItfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nNTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nOtrosCargosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nOtrosGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nSaldoCapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sDOIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFecha_ProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNumero_CreditoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sRubro_CuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTipo_MovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vAsiento_ContableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vCodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vCodigoEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNombreClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNombreMonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNroTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vSegDesgravamenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Monto {
            get {
                return this.MontoField;
            }
            set {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NRO_LINEA {
            get {
                return this.NRO_LINEAField;
            }
            set {
                this.NRO_LINEAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dFechaPago {
            get {
                return this.dFechaPagoField;
            }
            set {
                this.dFechaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dFechaVencimiento {
            get {
                return this.dFechaVencimientoField;
            }
            set {
                this.dFechaVencimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dFecha_Ingreso {
            get {
                return this.dFecha_IngresoField;
            }
            set {
                this.dFecha_IngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal dMonto_Aplicar {
            get {
                return this.dMonto_AplicarField;
            }
            set {
                this.dMonto_AplicarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal iImp_Mora {
            get {
                return this.iImp_MoraField;
            }
            set {
                this.iImp_MoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal iInt_Moratorio {
            get {
                return this.iInt_MoratorioField;
            }
            set {
                this.iInt_MoratorioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iOficina_Pago {
            get {
                return this.iOficina_PagoField;
            }
            set {
                this.iOficina_PagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nImpDepositado {
            get {
                return this.nImpDepositadoField;
            }
            set {
                this.nImpDepositadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nImp_Origen {
            get {
                return this.nImp_OrigenField;
            }
            set {
                this.nImp_OrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nItf {
            get {
                return this.nItfField;
            }
            set {
                this.nItfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nNTransaccion {
            get {
                return this.nNTransaccionField;
            }
            set {
                this.nNTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nOtrosCargos {
            get {
                return this.nOtrosCargosField;
            }
            set {
                this.nOtrosCargosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nOtrosGastos {
            get {
                return this.nOtrosGastosField;
            }
            set {
                this.nOtrosGastosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nSaldoCapital {
            get {
                return this.nSaldoCapitalField;
            }
            set {
                this.nSaldoCapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDOI {
            get {
                return this.sDOIField;
            }
            set {
                this.sDOIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFecha_Proceso {
            get {
                return this.sFecha_ProcesoField;
            }
            set {
                this.sFecha_ProcesoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMoneda {
            get {
                return this.sMonedaField;
            }
            set {
                this.sMonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNumero_Credito {
            get {
                return this.sNumero_CreditoField;
            }
            set {
                this.sNumero_CreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sRubro_Cuenta {
            get {
                return this.sRubro_CuentaField;
            }
            set {
                this.sRubro_CuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sTipo_Movimiento {
            get {
                return this.sTipo_MovimientoField;
            }
            set {
                this.sTipo_MovimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vAsiento_Contable {
            get {
                return this.vAsiento_ContableField;
            }
            set {
                this.vAsiento_ContableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vCodigoError {
            get {
                return this.vCodigoErrorField;
            }
            set {
                this.vCodigoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vCodigoEstado {
            get {
                return this.vCodigoEstadoField;
            }
            set {
                this.vCodigoEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vDescripcion {
            get {
                return this.vDescripcionField;
            }
            set {
                this.vDescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vMoneda {
            get {
                return this.vMonedaField;
            }
            set {
                this.vMonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNombreCliente {
            get {
                return this.vNombreClienteField;
            }
            set {
                this.vNombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNombreMoneda {
            get {
                return this.vNombreMonedaField;
            }
            set {
                this.vNombreMonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNroTicket {
            get {
                return this.vNroTicketField;
            }
            set {
                this.vNroTicketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vObservacion {
            get {
                return this.vObservacionField;
            }
            set {
                this.vObservacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vReferencia {
            get {
                return this.vReferenciaField;
            }
            set {
                this.vReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vSegDesgravamen {
            get {
                return this.vSegDesgravamenField;
            }
            set {
                this.vSegDesgravamenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnAfectacionesMasivasReporteCabecera", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnAfectacionesMasivasReporteCabecera : UtilitarioCrk.wsSeguridad.enBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iNumeroRegistrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iNumeroRegistrosCorrectosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iNumeroRegistrosFallidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal nNumeroTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCargoEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCargoFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCargoHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCargoMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNombreUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iNumeroRegistros {
            get {
                return this.iNumeroRegistrosField;
            }
            set {
                this.iNumeroRegistrosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iNumeroRegistrosCorrectos {
            get {
                return this.iNumeroRegistrosCorrectosField;
            }
            set {
                this.iNumeroRegistrosCorrectosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iNumeroRegistrosFallidos {
            get {
                return this.iNumeroRegistrosFallidosField;
            }
            set {
                this.iNumeroRegistrosFallidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal nNumeroTicket {
            get {
                return this.nNumeroTicketField;
            }
            set {
                this.nNumeroTicketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCargoEstado {
            get {
                return this.sCargoEstadoField;
            }
            set {
                this.sCargoEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCargoFecha {
            get {
                return this.sCargoFechaField;
            }
            set {
                this.sCargoFechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCargoHora {
            get {
                return this.sCargoHoraField;
            }
            set {
                this.sCargoHoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCargoMensaje {
            get {
                return this.sCargoMensajeField;
            }
            set {
                this.sCargoMensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCodigoUsuario {
            get {
                return this.sCodigoUsuarioField;
            }
            set {
                this.sCodigoUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFechaFin {
            get {
                return this.sFechaFinField;
            }
            set {
                this.sFechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFechaInicio {
            get {
                return this.sFechaInicioField;
            }
            set {
                this.sFechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreProceso {
            get {
                return this.sNombreProcesoField;
            }
            set {
                this.sNombreProcesoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombreUsuario {
            get {
                return this.sNombreUsuarioField;
            }
            set {
                this.sNombreUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnExportarDeudasCA", Namespace="http://schemas.datacontract.org/2004/07/SatelitesEN")]
    [System.SerializableAttribute()]
    public partial class EnExportarDeudasCA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] bFileBytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sFileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] bFileBytes {
            get {
                return this.bFileBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.bFileBytesField, value) != true)) {
                    this.bFileBytesField = value;
                    this.RaisePropertyChanged("bFileBytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sFileName {
            get {
                return this.sFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.sFileNameField, value) != true)) {
                    this.sFileNameField = value;
                    this.RaisePropertyChanged("sFileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsGestion.IwsGestion")]
    public interface IwsGestion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsGeneracionDeudaCV", ReplyAction="http://tempuri.org/IwsGestion/wsGeneracionDeudaCVResponse")]
        OperacionesTopazWeb.wsGestion.EnCorresponsalia wsGeneracionDeudaCV(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsGeneracionDeudaCV", ReplyAction="http://tempuri.org/IwsGestion/wsGeneracionDeudaCVResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnCorresponsalia> wsGeneracionDeudaCVAsync(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsGeneracionDeuda", ReplyAction="http://tempuri.org/IwsGestion/wsGeneracionDeudaResponse")]
        OperacionesTopazWeb.wsGestion.EnCorresponsalia wsGeneracionDeuda(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsGeneracionDeuda", ReplyAction="http://tempuri.org/IwsGestion/wsGeneracionDeudaResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnCorresponsalia> wsGeneracionDeudaAsync(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsGeneracionPagos", ReplyAction="http://tempuri.org/IwsGestion/wsGeneracionPagosResponse")]
        OperacionesTopazWeb.wsGestion.EnCorresponsalia wsGeneracionPagos(string vRuta, string vNombre, OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsGeneracionPagos", ReplyAction="http://tempuri.org/IwsGestion/wsGeneracionPagosResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnCorresponsalia> wsGeneracionPagosAsync(string vRuta, string vNombre, OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsGeneracionPagosCA", ReplyAction="http://tempuri.org/IwsGestion/wsGeneracionPagosCAResponse")]
        OperacionesTopazWeb.wsGestion.EnCorresponsalia wsGeneracionPagosCA(string vRuta, string vNombre, OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsGeneracionPagosCA", ReplyAction="http://tempuri.org/IwsGestion/wsGeneracionPagosCAResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnCorresponsalia> wsGeneracionPagosCAAsync(string vRuta, string vNombre, OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsObtenerArchivo", ReplyAction="http://tempuri.org/IwsGestion/wsObtenerArchivoResponse")]
        byte[] wsObtenerArchivo(int piFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsObtenerArchivo", ReplyAction="http://tempuri.org/IwsGestion/wsObtenerArchivoResponse")]
        System.Threading.Tasks.Task<byte[]> wsObtenerArchivoAsync(int piFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsObtenerPagos", ReplyAction="http://tempuri.org/IwsGestion/wsObtenerPagosResponse")]
        byte[] wsObtenerPagos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsObtenerPagos", ReplyAction="http://tempuri.org/IwsGestion/wsObtenerPagosResponse")]
        System.Threading.Tasks.Task<byte[]> wsObtenerPagosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsObtenerPagosCA", ReplyAction="http://tempuri.org/IwsGestion/wsObtenerPagosCAResponse")]
        byte[] wsObtenerPagosCA(int iIdPagosCA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsObtenerPagosCA", ReplyAction="http://tempuri.org/IwsGestion/wsObtenerPagosCAResponse")]
        System.Threading.Tasks.Task<byte[]> wsObtenerPagosCAAsync(int iIdPagosCA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsObtenerPagosCV", ReplyAction="http://tempuri.org/IwsGestion/wsObtenerPagosCVResponse")]
        byte[] wsObtenerPagosCV();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsObtenerPagosCV", ReplyAction="http://tempuri.org/IwsGestion/wsObtenerPagosCVResponse")]
        System.Threading.Tasks.Task<byte[]> wsObtenerPagosCVAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/WsListarPago", ReplyAction="http://tempuri.org/IwsGestion/WsListarPagoResponse")]
        OperacionesTopazWeb.wsGestion.EnCorresponsaliaDescargarPagos[] WsListarPago(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros, string fechaInicio, string fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/WsListarPago", ReplyAction="http://tempuri.org/IwsGestion/WsListarPagoResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnCorresponsaliaDescargarPagos[]> WsListarPagoAsync(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros, string fechaInicio, string fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/WsReporteAfectacionesMasivasCabecera", ReplyAction="http://tempuri.org/IwsGestion/WsReporteAfectacionesMasivasCabeceraResponse")]
        OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera[] WsReporteAfectacionesMasivasCabecera(OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera oParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/WsReporteAfectacionesMasivasCabecera", ReplyAction="http://tempuri.org/IwsGestion/WsReporteAfectacionesMasivasCabeceraResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera[]> WsReporteAfectacionesMasivasCabeceraAsync(OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera oParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsExportarPagos", ReplyAction="http://tempuri.org/IwsGestion/wsExportarPagosResponse")]
        byte[] wsExportarPagos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsExportarPagos", ReplyAction="http://tempuri.org/IwsGestion/wsExportarPagosResponse")]
        System.Threading.Tasks.Task<byte[]> wsExportarPagosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsExportarAfectacionesMasivas", ReplyAction="http://tempuri.org/IwsGestion/wsExportarAfectacionesMasivasResponse")]
        byte[] wsExportarAfectacionesMasivas(OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera oParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsExportarAfectacionesMasivas", ReplyAction="http://tempuri.org/IwsGestion/wsExportarAfectacionesMasivasResponse")]
        System.Threading.Tasks.Task<byte[]> wsExportarAfectacionesMasivasAsync(OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera oParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsExportarDeudasCA", ReplyAction="http://tempuri.org/IwsGestion/wsExportarDeudasCAResponse")]
        OperacionesTopazWeb.wsGestion.EnExportarDeudasCA wsExportarDeudasCA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsGestion/wsExportarDeudasCA", ReplyAction="http://tempuri.org/IwsGestion/wsExportarDeudasCAResponse")]
        System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnExportarDeudasCA> wsExportarDeudasCAAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsGestionChannel : OperacionesTopazWeb.wsGestion.IwsGestion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsGestionClient : System.ServiceModel.ClientBase<OperacionesTopazWeb.wsGestion.IwsGestion>, OperacionesTopazWeb.wsGestion.IwsGestion {
        
        public IwsGestionClient() {
        }
        
        public IwsGestionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsGestionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsGestionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsGestionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OperacionesTopazWeb.wsGestion.EnCorresponsalia wsGeneracionDeudaCV(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros) {
            return base.Channel.wsGeneracionDeudaCV(Parametros);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnCorresponsalia> wsGeneracionDeudaCVAsync(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros) {
            return base.Channel.wsGeneracionDeudaCVAsync(Parametros);
        }
        
        public OperacionesTopazWeb.wsGestion.EnCorresponsalia wsGeneracionDeuda(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros) {
            return base.Channel.wsGeneracionDeuda(Parametros);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnCorresponsalia> wsGeneracionDeudaAsync(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros) {
            return base.Channel.wsGeneracionDeudaAsync(Parametros);
        }
        
        public OperacionesTopazWeb.wsGestion.EnCorresponsalia wsGeneracionPagos(string vRuta, string vNombre, OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros) {
            return base.Channel.wsGeneracionPagos(vRuta, vNombre, Parametros);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnCorresponsalia> wsGeneracionPagosAsync(string vRuta, string vNombre, OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros) {
            return base.Channel.wsGeneracionPagosAsync(vRuta, vNombre, Parametros);
        }
        
        public OperacionesTopazWeb.wsGestion.EnCorresponsalia wsGeneracionPagosCA(string vRuta, string vNombre, OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros) {
            return base.Channel.wsGeneracionPagosCA(vRuta, vNombre, Parametros);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnCorresponsalia> wsGeneracionPagosCAAsync(string vRuta, string vNombre, OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros) {
            return base.Channel.wsGeneracionPagosCAAsync(vRuta, vNombre, Parametros);
        }
        
        public byte[] wsObtenerArchivo(int piFlag) {
            return base.Channel.wsObtenerArchivo(piFlag);
        }
        
        public System.Threading.Tasks.Task<byte[]> wsObtenerArchivoAsync(int piFlag) {
            return base.Channel.wsObtenerArchivoAsync(piFlag);
        }
        
        public byte[] wsObtenerPagos() {
            return base.Channel.wsObtenerPagos();
        }
        
        public System.Threading.Tasks.Task<byte[]> wsObtenerPagosAsync() {
            return base.Channel.wsObtenerPagosAsync();
        }
        
        public byte[] wsObtenerPagosCA(int iIdPagosCA) {
            return base.Channel.wsObtenerPagosCA(iIdPagosCA);
        }
        
        public System.Threading.Tasks.Task<byte[]> wsObtenerPagosCAAsync(int iIdPagosCA) {
            return base.Channel.wsObtenerPagosCAAsync(iIdPagosCA);
        }
        
        public byte[] wsObtenerPagosCV() {
            return base.Channel.wsObtenerPagosCV();
        }
        
        public System.Threading.Tasks.Task<byte[]> wsObtenerPagosCVAsync() {
            return base.Channel.wsObtenerPagosCVAsync();
        }
        
        public OperacionesTopazWeb.wsGestion.EnCorresponsaliaDescargarPagos[] WsListarPago(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros, string fechaInicio, string fechaFin) {
            return base.Channel.WsListarPago(Parametros, fechaInicio, fechaFin);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnCorresponsaliaDescargarPagos[]> WsListarPagoAsync(OperacionesTopazWeb.wsGestion.EnCorresponsaliaParametros Parametros, string fechaInicio, string fechaFin) {
            return base.Channel.WsListarPagoAsync(Parametros, fechaInicio, fechaFin);
        }
        
        public OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera[] WsReporteAfectacionesMasivasCabecera(OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera oParametros) {
            return base.Channel.WsReporteAfectacionesMasivasCabecera(oParametros);
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera[]> WsReporteAfectacionesMasivasCabeceraAsync(OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera oParametros) {
            return base.Channel.WsReporteAfectacionesMasivasCabeceraAsync(oParametros);
        }
        
        public byte[] wsExportarPagos() {
            return base.Channel.wsExportarPagos();
        }
        
        public System.Threading.Tasks.Task<byte[]> wsExportarPagosAsync() {
            return base.Channel.wsExportarPagosAsync();
        }
        
        public byte[] wsExportarAfectacionesMasivas(OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera oParametros) {
            return base.Channel.wsExportarAfectacionesMasivas(oParametros);
        }
        
        public System.Threading.Tasks.Task<byte[]> wsExportarAfectacionesMasivasAsync(OperacionesTopazWeb.wsGestion.EnAfectacionesMasivasReporteCabecera oParametros) {
            return base.Channel.wsExportarAfectacionesMasivasAsync(oParametros);
        }
        
        public OperacionesTopazWeb.wsGestion.EnExportarDeudasCA wsExportarDeudasCA() {
            return base.Channel.wsExportarDeudasCA();
        }
        
        public System.Threading.Tasks.Task<OperacionesTopazWeb.wsGestion.EnExportarDeudasCA> wsExportarDeudasCAAsync() {
            return base.Channel.wsExportarDeudasCAAsync();
        }
    }
}
